spring:
  datasource:
    url: "jdbc:h2:mem:run-the-bank"
    username: "admin"
    password: "admin"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
  h2:
    console:
      enabled: true

run-the-bank:
  url:
    notification: "https://run.mocky.io/v3/9769bf3a-b0b6-477a-9ff5-91f63010c9d3"

logging:
  level:
    com:
      challenge:
        backend:
          runthebank: debug